version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.0
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: .
      dockerfile: development/dockerfiles/elasticsearch
    ports:
      - "9200:9200"
    environment:
      network.bind_host: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs

  event-listener:
    container_name: event-listener
    image: event-listener
    build:
      context: .
      dockerfile: development/dockerfiles/event-listener
    depends_on:
      - postgres
      - elasticsearch
    command:
      >
      /bin/bash -c "wait-for.sh -t 0 -q origin-js:8080 --
      wait-for.sh -t 0 -q elasticsearch:9200 --
      npm run migrate &&
      npm run start:listener"
