version: "3"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10.0
    environment:
      - POSTGRES_USER=origin
      - POSTGRES_PASSWORD=origin
      - POSTGRES_DB=origin

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    build:
      context: .
      dockerfile: development/dockerfiles/elasticsearch
    ports:
      - "9200:9200"
    environment:
      network.bind_host: 0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - default

  ipfs-proxy:
    container_name: ipfs-proxy
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    ports:
      - "9999:9999"
    environment:
      - IPFS_API_URL=http://origin-js:5002
      - IPFS_GATEWAY_URL=http://origin-js:8080
    volumes:
      - ./ipfs-proxy:/app/ipfs-proxy
    command:
      >
      /bin/bash -c "npm run start --prefix ipfs-proxy"

  # NOTE/TODO: This container is only responsible for running ganache and IPFS,
  # this functionality should be moved to dedicated containers
  origin-js:
    container_name: origin-js
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    ports:
      - "8545:8545"  # Ganache
    volumes:
      # Addresses for deployment of contracts to local blockchain will get
      # written to the build files
      - ./origin-contracts/build:/app/origin-contracts/build
      - ./origin-js/scripts:/app/origin-js/scripts
    command: npm run start --prefix origin-js

  origin-discovery:
    container_name: origin-discovery
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    volumes:
      - ./origin-js/src:/app/origin-js/src
      - ./origin-discovery/src:/app/origin-discovery/src
    environment:
      - DATABASE_URL=postgres://origin:origin@postgres/origin
      - ELASTICSEARCH_HOST=elasticsearch:9200
    depends_on:
      - origin-js
      - postgres
      - elasticsearch
    ports:
      - "4000:4000"
    command: npm run start:discovery --prefix origin-discovery

  event-listener:
    container_name: event-listener
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    volumes:
      - ./origin-contracts/build:/app/origin-contracts/build
      - ./origin-js/src:/app/origin-js/src
      - ./origin-discovery/src:/app/origin-discovery/src
      - ./development/envfiles/event-listener.env:/app/origin-discovery/.env
    depends_on:
      - origin-js
      - postgres
      - elasticsearch
      - ipfs-proxy
    command:
      >
      /bin/bash -c "wait-for.sh -t 0 -q origin-js:8080 --
      wait-for.sh -t 0 -q elasticsearch:9200 --
      npm run migrate --prefix origin-discovery &&
      npm run start:listener --prefix origin-discovery"

  origin-messaging:
    container_name: origin-messaging
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    ports:
      - "9012:9012"
    volumes:
      - ./origin-messaging/src:/app/origin-messaging/src
      - ./development/.ipfs:/app/origin-messaging/ipfs
    environment:
      - MESSAGING_NAMESPACE=dev
    command: npm run start --prefix origin-messaging

  origin-bridge:
    container_name: origin-bridge
    image: origin-bridge
    build:
      context: .
      dockerfile: development/dockerfiles/origin-bridge
    volumes:
      - ./origin-bridge:/app
      # Set the envfile from the local envfile
      - ./development/envfiles/origin-bridge.env:/app/.env
    depends_on:
      - postgres
    environment:
      - FLASK_APP=/app/main.py
      - FLASK_DEBUG=True
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    command: /bin/bash -c "flask db upgrade && flask run --host=0.0.0.0"

  origin-notifications:
    container_name: origin-notifications
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    volumes:
      - ./origin-notifications/src:/app/origin-notifications/src
      - ./development/envfiles/origin-notifications.env:/app/.env
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://origin:origin@postgres/origin
    ports:
      - "3456:3456"
    command:
      >
      /bin/bash -c "wait-for.sh -t 0 -q postgres:5432 --
      npm run migrate --prefix origin-notifications &&
      npm run start --prefix origin-notifications"

  origin-dapp:
    container_name: origin-dapp
    image: origin
    build:
      context: .
      dockerfile: development/dockerfiles/origin
    volumes:
      # Include origin-contracts build files so the DApp has access to the
      # address of the contracts on the local blockchain
      - ./origin-contracts/build:/app/origin-contracts/build
      - ./origin-js/src:/app/origin-js/src
      # Mount origin-dapp inside the container
      - ./origin-dapp/src:/app/origin-dapp/src
      - ./origin-dapp/public:/app/origin-dapp/public
      - ./origin-dapp/webpack.config.js:/app/origin-dapp/webpack.config.js
      # Set the envfile from the local envfile
      - ./development/envfiles/origin-dapp.env:/app/origin-dapp/.env
      - ./development/.ipfs:/ipfs
    depends_on:
      - ipfs-proxy
      - event-listener
      - origin-js
      - origin-discovery
      - origin-messaging
      - origin-bridge
      - origin-notifications
    ports:
      - "127.0.0.1:3000:3000"
    command:
      # Waits for origin-messaging to start then uses a script to read the
      # origin-messaging IPFS peer id and write the configuration key/pair to
      # the .env file.
      >
      /bin/bash -c "wait-for.sh -t 0 origin-messaging:9012 &&
      . set-ipfs-swarm.sh /ipfs/config &&
      wait-for.sh -t 0 origin-js:8080 --
      npm run start:development --prefix origin-dapp -- --host 0.0.0.0"
