databaseInstance: origin-214503:us-west1:prod

# origin-bridge
bridgeImage: origin-bridge
bridgeImageTag: '916795e'

# origin-dapp
dappImage: origin-dapp
dappImageTag: 'cca4e4b'

# Mainnet nodes
gethTxReplicas: 1

# IPFS server
ipfsImageTag: ipfs/go-ipfs
ipfsImageTag: master

faucetImage: origin-faucet
faucetImageTag: '28438d2'

eventlistenerImage: event-listener
eventlistenerImageTag: '9509a68'

discoveryImage: origin-discovery
discoveryImageTag: '6e22b35'

# OrbitDB
messagingImage: origin-messaging
messagingImageTag: '3104d23'

# origin-notifications
notificationsImage: origin-notifications
notificationsImageTag: 'latest'
